# Generated by Django 5.0.1 on 2024-02-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('description', models.TextField(verbose_name='Описание')),
                ('experience', models.IntegerField(verbose_name='Опыт Работы')),
                ('project', models.IntegerField(verbose_name='Кол-во Проектов')),
                ('happyclient', models.IntegerField(verbose_name='Кол-во довольнных клиентов')),
                ('unhappyclient', models.IntegerField(verbose_name='Кол-во Недовольныхх клиентов')),
            ],
            options={
                'verbose_name': 'Настройка страницы обо мне',
            },
        ),
    ]
