# Generated by Django 5.0.1 on 2024-02-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Базовые настройки', 'verbose_name_plural': 'Базавая настройка'},
        ),
    ]
