# Generated by Django 5.0.1 on 2024-02-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Скиллы')),
            ],
            options={
                'verbose_name': 'Настройки скиллов',
                'verbose_name_plural': 'Настройка склиллов',
            },
        ),
    ]
