# Generated by Django 5.0.1 on 2024-02-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Язык програмиравание'),
            preserve_default=False,
        ),
    ]
