# Generated by Django 5.0.1 on 2024-02-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='year2',
            field=models.CharField(max_length=255, verbose_name='Год2'),
        ),
    ]
