# Generated by Django 5.0.2 on 2024-02-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
