# Generated by Django 5.0.1 on 2024-02-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Направление')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('image', models.ImageField(upload_to='images', verbose_name='Фотография')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Инстаграм')),
                ('telegram', models.URLField(verbose_name='Телеграмм')),
                ('experience', models.CharField(max_length=255, verbose_name='Опыт работы')),
                ('project', models.CharField(max_length=255, verbose_name='Кол-во Проектов')),
                ('client', models.CharField(max_length=255, verbose_name='Кол-во Клиентов')),
            ],
            options={
                'verbose_name': 'Настройки главной страницы',
                'verbose_name_plural': 'Настройка главной страницы',
            },
        ),
    ]
