# Generated by Django 5.0.1 on 2024-02-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Телеграмм'),
        ),
    ]
