# Generated by Django 5.0.1 on 2024-02-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_index_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libary', models.CharField(max_length=255, verbose_name='Знание библеотек')),
                ('languages', models.CharField(blank=True, max_length=255, null=True, verbose_name='Знание языков')),
            ],
            options={
                'verbose_name': 'Настройки Слайда',
                'verbose_name_plural': 'Настройка Слайда',
            },
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Базовые настройки', 'verbose_name_plural': 'Базавая настройка'},
        ),
    ]
