# Generated by Django 5.0.2 on 2024-02-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_slide_languages_alter_slide_libary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Фогорафия')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Предложение услуг',
                'verbose_name_plural': 'Предложение услуг',
            },
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'База ', 'verbose_name_plural': 'База'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': ' Слайд', 'verbose_name_plural': 'Слайд'},
        ),
    ]
