# Generated by Django 5.0.2 on 2024-02-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offernig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title2', models.CharField(max_length=255, verbose_name='Название2')),
                ('image', models.ImageField(max_length=255, upload_to='', verbose_name='Фотография')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Предложение',
            },
        ),
    ]
