# Generated by Django 5.0.1 on 2024-02-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Зоголовок')),
                ('image', models.ImageField(upload_to='images', verbose_name='Фотография')),
                ('desription', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Большой  баннер',
                'verbose_name_plural': ' Большой баннер',
            },
        ),
        migrations.CreateModel(
            name='LongBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Зоголовок')),
                ('image', models.ImageField(upload_to='images', verbose_name='Фотография')),
                ('desription', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Длинный баннер',
                'verbose_name_plural': 'Длинный баннер',
            },
        ),
        migrations.CreateModel(
            name='SmallBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Зоголовок')),
                ('image', models.ImageField(upload_to='images', verbose_name='Фотография')),
                ('desription', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Маленкий баннер',
                'verbose_name_plural': 'Маленкий баннер',
            },
        ),
        migrations.CreateModel(
            name='SquareBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Зоголовок')),
                ('image', models.ImageField(upload_to='images', verbose_name='Фотография')),
                ('desription', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Длинный баннер',
                'verbose_name_plural': 'Длинный баннер',
            },
        ),
    ]
