# Generated by Django 5.0.2 on 2024-02-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squarebanner',
            options={'verbose_name': 'квадратный баннер', 'verbose_name_plural': 'квадратный баннер'},
        ),
    ]
